import { ClientRecord, LoanApplicationRecord, PartnerStatRecord, SemanticMemoryRecord } from "@/server/crm-assistant/types"

export const demoClients: ClientRecord[] = [
  {
    id: "client_1",
    partnerId: "partner_1",
    fullName: "Amit Verma",
    city: "Delhi",
    employmentType: "salaried",
    monthlyIncome: 85000,
    existingEmi: 18000,
    requestedLoanAmount: 2200000,
    cibilScore: 782,
    notes: ["Good salary stability", "Employer documents already verified"],
  },
  {
    id: "client_2",
    partnerId: "partner_1",
    fullName: "Neha Saini",
    city: "Noida",
    employmentType: "self_employed",
    monthlyIncome: 62000,
    existingEmi: 29000,
    requestedLoanAmount: 1800000,
    cibilScore: 641,
    notes: ["Banking surrogates needed", "GST trail inconsistent"],
  },
  {
    id: "client_3",
    partnerId: "partner_1",
    fullName: "Karan Mehta",
    city: "Gurugram",
    employmentType: "salaried",
    monthlyIncome: 54000,
    existingEmi: 16000,
    requestedLoanAmount: 1400000,
    cibilScore: 698,
    notes: ["Payslips shared but bank statement missing"],
  },
]

export const demoApplications: LoanApplicationRecord[] = [
  {
    id: "app_1",
    clientId: "client_1",
    partnerId: "partner_1",
    lenderName: "HDFC Bank",
    productType: "Home Loan",
    stage: "Under Review",
    status: "active",
    requestedAmount: 2200000,
    sanctionedAmount: 2000000,
    proposedEmi: 21500,
    missingDocuments: [],
    lastActivityAt: "2026-03-23T10:00:00.000Z",
    createdAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "app_2",
    clientId: "client_2",
    partnerId: "partner_1",
    lenderName: "ICICI Bank",
    productType: "Business Loan",
    stage: "Docs Pending",
    status: "active",
    requestedAmount: 1800000,
    proposedEmi: 33500,
    missingDocuments: ["GST Returns", "Latest Bank Statement"],
    lastActivityAt: "2026-03-21T16:30:00.000Z",
    createdAt: "2026-03-05T11:15:00.000Z",
  },
  {
    id: "app_3",
    clientId: "client_3",
    partnerId: "partner_1",
    lenderName: "Axis Bank",
    productType: "Personal Loan",
    stage: "Docs Pending",
    status: "active",
    requestedAmount: 1400000,
    proposedEmi: 30100,
    missingDocuments: ["Salary Account Statement", "Form 16"],
    lastActivityAt: "2026-03-24T09:20:00.000Z",
    createdAt: "2026-03-08T14:10:00.000Z",
  },
]

export const demoPartnerStats: PartnerStatRecord[] = [
  {
    partnerId: "partner_1",
    month: "2026-02",
    leads: 75,
    submitted: 50,
    approvals: 34,
    disbursals: 28,
    rejected: 10,
    docsPending: 9,
  },
  {
    partnerId: "partner_1",
    month: "2026-03",
    leads: 82,
    submitted: 48,
    approvals: 25,
    disbursals: 19,
    rejected: 11,
    docsPending: 16,
  },
]

export const demoSemanticMemories: SemanticMemoryRecord[] = [
  {
    id: "mem_1",
    partnerId: "partner_1",
    clientId: "client_2",
    content: "Neha Saini was delayed last week because GST returns were not uploaded and banking was inconsistent.",
    summary: "Neha Saini has recurring documentation and banking consistency issues.",
    tags: ["docs", "banking", "business-loan"],
    createdAt: "2026-03-20T10:00:00.000Z",
  },
  {
    id: "mem_2",
    partnerId: "partner_1",
    clientId: "client_3",
    content: "Karan Mehta asked for a quick sanction, but the salary account statement is still missing.",
    summary: "Karan Mehta is speed-sensitive but blocked by salary account documents.",
    tags: ["docs", "salary", "priority"],
    createdAt: "2026-03-24T10:00:00.000Z",
  },
]
