import { upsertLendingProducts } from "@/lib/knowledgeBase"
import type { LendingProduct } from "@/types/agents"

const now = new Date("2025-02-15T00:00:00.000Z")

const seedProducts: LendingProduct[] = [
  {
    productType: "personal_loan",
    lenderName: "HDFC Bank",
    interestRateMin: 10.5,
    interestRateMax: 24,
    processingFeePercent: 2,
    minLoanAmount: 50000,
    maxLoanAmount: 4000000,
    minTenureMonths: 12,
    maxTenureMonths: 72,
    tatDays: 3,
    minCibilScore: 700,
    minMonthlyIncome: 25000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "pan", "aadhaar"], selfEmployed: ["itr", "bank_statement", "pan", "aadhaar"] },
    eligibilityCriteria: "Minimum 2 years work experience and 1 year at current employer.",
    prepaymentCharges: "Up to 4% foreclosure charge depending on tenure.",
    specialFeatures: ["top-up available", "digital KYC"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "personal_loan",
    lenderName: "SBI",
    interestRateMin: 11.15,
    interestRateMax: 15.3,
    processingFeePercent: 1.5,
    minLoanAmount: 100000,
    maxLoanAmount: 3000000,
    minTenureMonths: 12,
    maxTenureMonths: 72,
    tatDays: 5,
    minCibilScore: 680,
    minMonthlyIncome: 20000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "pan", "aadhaar"], selfEmployed: ["itr", "gst_returns", "pan", "aadhaar"] },
    eligibilityCriteria: "Salary account holders get preferential processing.",
    prepaymentCharges: "Nil after 6 EMIs for floating products.",
    specialFeatures: ["competitive rates", "public sector reliability"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "personal_loan",
    lenderName: "ICICI Bank",
    interestRateMin: 10.85,
    interestRateMax: 19,
    processingFeePercent: 2.25,
    minLoanAmount: 50000,
    maxLoanAmount: 5000000,
    minTenureMonths: 12,
    maxTenureMonths: 72,
    tatDays: 2,
    minCibilScore: 700,
    minMonthlyIncome: 30000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "pan", "aadhaar"], selfEmployed: ["itr", "bank_statement", "pan", "aadhaar"] },
    eligibilityCriteria: "Instant approval for pre-approved customers.",
    prepaymentCharges: "3-5% depending on month of closure.",
    specialFeatures: ["instant disbursal", "pre-approved offers"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "personal_loan",
    lenderName: "Axis Bank",
    interestRateMin: 10.49,
    interestRateMax: 22,
    processingFeePercent: 2,
    minLoanAmount: 100000,
    maxLoanAmount: 4000000,
    minTenureMonths: 12,
    maxTenureMonths: 84,
    tatDays: 3,
    minCibilScore: 700,
    minMonthlyIncome: 25000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "pan", "aadhaar"], selfEmployed: ["itr", "gst_returns", "pan", "aadhaar"] },
    eligibilityCriteria: "At least 1 year continuity in current business/employment.",
    prepaymentCharges: "Applicable as per sanction letter.",
    specialFeatures: ["quick sanction", "higher tenure"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "personal_loan",
    lenderName: "Kotak Mahindra Bank",
    interestRateMin: 10.99,
    interestRateMax: 24,
    processingFeePercent: 2.5,
    minLoanAmount: 100000,
    maxLoanAmount: 3500000,
    minTenureMonths: 12,
    maxTenureMonths: 72,
    tatDays: 4,
    minCibilScore: 700,
    minMonthlyIncome: 30000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "pan", "aadhaar"], selfEmployed: ["itr", "bank_statement", "pan", "aadhaar"] },
    eligibilityCriteria: "Metro and tier-1 city applicants preferred for instant process.",
    prepaymentCharges: "4% on outstanding principal.",
    specialFeatures: ["digital documentation", "top-up option"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "personal_loan",
    lenderName: "Bajaj Finserv",
    interestRateMin: 11,
    interestRateMax: 26,
    processingFeePercent: 3,
    minLoanAmount: 40000,
    maxLoanAmount: 5500000,
    minTenureMonths: 12,
    maxTenureMonths: 96,
    tatDays: 2,
    minCibilScore: 685,
    minMonthlyIncome: 22000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "pan"], selfEmployed: ["itr", "business_registration", "pan"] },
    eligibilityCriteria: "Flexible repayment products available for existing customers.",
    prepaymentCharges: "Foreclosure fee as per product variant.",
    specialFeatures: ["high loan amount", "flexi EMI"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "personal_loan",
    lenderName: "Tata Capital",
    interestRateMin: 10.99,
    interestRateMax: 24,
    processingFeePercent: 2.75,
    minLoanAmount: 75000,
    maxLoanAmount: 3500000,
    minTenureMonths: 12,
    maxTenureMonths: 72,
    tatDays: 3,
    minCibilScore: 690,
    minMonthlyIncome: 25000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "pan"], selfEmployed: ["itr", "bank_statement", "pan", "business_registration"] },
    eligibilityCriteria: "Stable income profile in salaried or self-employed category.",
    prepaymentCharges: "As per sanction terms.",
    specialFeatures: ["fast digital process", "custom tenure"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "home_loan",
    lenderName: "HDFC Bank",
    interestRateMin: 8.5,
    interestRateMax: 9.6,
    processingFeePercent: 0.5,
    processingFeeFixed: 3300,
    minLoanAmount: 500000,
    maxLoanAmount: 100000000,
    minTenureMonths: 60,
    maxTenureMonths: 360,
    tatDays: 10,
    minCibilScore: 700,
    minMonthlyIncome: 30000,
    documentsRequired: { salaried: ["salary_slip", "form_16", "bank_statement", "property_documents", "pan", "aadhaar"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan", "aadhaar"] },
    eligibilityCriteria: "FOIR generally up to 55%; property technical and legal clearance mandatory.",
    prepaymentCharges: "Nil on floating rate for individuals.",
    specialFeatures: ["balance transfer", "top-up available"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "home_loan",
    lenderName: "SBI",
    interestRateMin: 8.4,
    interestRateMax: 9.3,
    processingFeePercent: 0.35,
    minLoanAmount: 300000,
    maxLoanAmount: 100000000,
    minTenureMonths: 60,
    maxTenureMonths: 360,
    tatDays: 12,
    minCibilScore: 680,
    minMonthlyIncome: 25000,
    documentsRequired: { salaried: ["salary_slip", "form_16", "bank_statement", "property_documents", "pan", "aadhaar"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan", "aadhaar"] },
    eligibilityCriteria: "Max tenure linked to applicant retirement age and property profile.",
    prepaymentCharges: "Nil for floating home loans.",
    specialFeatures: ["women concession", "long tenure"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "home_loan",
    lenderName: "ICICI Bank",
    interestRateMin: 8.75,
    interestRateMax: 9.85,
    processingFeePercent: 0.5,
    minLoanAmount: 500000,
    maxLoanAmount: 70000000,
    minTenureMonths: 60,
    maxTenureMonths: 360,
    tatDays: 9,
    minCibilScore: 700,
    minMonthlyIncome: 30000,
    documentsRequired: { salaried: ["salary_slip", "form_16", "bank_statement", "property_documents", "pan", "aadhaar"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan", "aadhaar"] },
    eligibilityCriteria: "Property valuation and legal vetting mandatory before sanction.",
    prepaymentCharges: "Nil for floating individual borrowers.",
    specialFeatures: ["doorstep service", "digital sanction"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "home_loan",
    lenderName: "Axis Bank",
    interestRateMin: 8.75,
    interestRateMax: 10.4,
    processingFeePercent: 1,
    minLoanAmount: 300000,
    maxLoanAmount: 50000000,
    minTenureMonths: 36,
    maxTenureMonths: 360,
    tatDays: 8,
    minCibilScore: 700,
    minMonthlyIncome: 25000,
    documentsRequired: { salaried: ["salary_slip", "form_16", "bank_statement", "property_documents", "pan", "aadhaar"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan", "aadhaar"] },
    eligibilityCriteria: "FOIR and repayment track record considered for final sanction.",
    prepaymentCharges: "Nil for floating products under retail policy.",
    specialFeatures: ["balance transfer", "quick in-principle approval"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "home_loan",
    lenderName: "Kotak Mahindra Bank",
    interestRateMin: 8.7,
    interestRateMax: 10.2,
    processingFeePercent: 1,
    minLoanAmount: 500000,
    maxLoanAmount: 50000000,
    minTenureMonths: 60,
    maxTenureMonths: 240,
    tatDays: 9,
    minCibilScore: 700,
    minMonthlyIncome: 30000,
    documentsRequired: { salaried: ["salary_slip", "form_16", "bank_statement", "property_documents", "pan"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan"] },
    eligibilityCriteria: "Salaried and self-employed both supported with profile-based pricing.",
    prepaymentCharges: "Nil for floating individual borrowers.",
    specialFeatures: ["step-up EMI", "top-up"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "home_loan",
    lenderName: "Bajaj Finserv",
    interestRateMin: 8.75,
    interestRateMax: 11,
    processingFeePercent: 1,
    minLoanAmount: 300000,
    maxLoanAmount: 60000000,
    minTenureMonths: 36,
    maxTenureMonths: 384,
    tatDays: 7,
    minCibilScore: 700,
    minMonthlyIncome: 25000,
    documentsRequired: { salaried: ["salary_slip", "form_16", "bank_statement", "property_documents", "pan"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan", "business_registration"] },
    eligibilityCriteria: "Eligibility based on profile, income stability, and property quality.",
    prepaymentCharges: "As per sanction letter and product type.",
    specialFeatures: ["long tenure", "digital processing"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "home_loan",
    lenderName: "Tata Capital",
    interestRateMin: 8.75,
    interestRateMax: 10.75,
    processingFeePercent: 0.75,
    minLoanAmount: 500000,
    maxLoanAmount: 50000000,
    minTenureMonths: 60,
    maxTenureMonths: 300,
    tatDays: 8,
    minCibilScore: 695,
    minMonthlyIncome: 25000,
    documentsRequired: { salaried: ["salary_slip", "form_16", "bank_statement", "property_documents", "pan"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan", "business_registration"] },
    eligibilityCriteria: "Stable repayment profile and clean property title required.",
    prepaymentCharges: "Nil or limited for floating retail variants.",
    specialFeatures: ["balance transfer", "customer support"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "lap",
    lenderName: "HDFC Bank",
    interestRateMin: 9.75,
    interestRateMax: 13.5,
    processingFeePercent: 1,
    minLoanAmount: 1000000,
    maxLoanAmount: 50000000,
    minTenureMonths: 60,
    maxTenureMonths: 180,
    tatDays: 9,
    minCibilScore: 700,
    minMonthlyIncome: 40000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "property_documents", "pan", "aadhaar"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan", "business_registration"] },
    eligibilityCriteria: "LTV up to 60% depending on property and profile.",
    prepaymentCharges: "Applicable as per sanction terms.",
    specialFeatures: ["balance transfer", "overdraft option"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "lap",
    lenderName: "SBI",
    interestRateMin: 10.15,
    interestRateMax: 12.25,
    processingFeePercent: 1,
    minLoanAmount: 1000000,
    maxLoanAmount: 30000000,
    minTenureMonths: 60,
    maxTenureMonths: 180,
    tatDays: 12,
    minCibilScore: 680,
    minMonthlyIncome: 35000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "property_documents", "pan"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan"] },
    eligibilityCriteria: "Residential/commercial property accepted subject to legal technical checks.",
    prepaymentCharges: "As applicable per scheme.",
    specialFeatures: ["public sector pricing", "transparent fees"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "lap",
    lenderName: "ICICI Bank",
    interestRateMin: 10.25,
    interestRateMax: 15,
    processingFeePercent: 1.5,
    minLoanAmount: 1000000,
    maxLoanAmount: 50000000,
    minTenureMonths: 36,
    maxTenureMonths: 180,
    tatDays: 8,
    minCibilScore: 700,
    minMonthlyIncome: 40000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "property_documents", "pan"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan", "business_registration"] },
    eligibilityCriteria: "LTV and repayment ability jointly evaluated.",
    prepaymentCharges: "As per sanction terms.",
    specialFeatures: ["fast sanction", "top-up on existing loans"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "lap",
    lenderName: "Axis Bank",
    interestRateMin: 10,
    interestRateMax: 16,
    processingFeePercent: 1.5,
    minLoanAmount: 1500000,
    maxLoanAmount: 50000000,
    minTenureMonths: 36,
    maxTenureMonths: 240,
    tatDays: 7,
    minCibilScore: 700,
    minMonthlyIncome: 35000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "property_documents", "pan"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan", "business_registration"] },
    eligibilityCriteria: "LTV typically capped at 60% subject to valuation.",
    prepaymentCharges: "Applicable as per policy.",
    specialFeatures: ["flexible tenure", "structured repayment"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "lap",
    lenderName: "Kotak Mahindra Bank",
    interestRateMin: 10.5,
    interestRateMax: 14.5,
    processingFeePercent: 1.5,
    minLoanAmount: 1000000,
    maxLoanAmount: 30000000,
    minTenureMonths: 36,
    maxTenureMonths: 180,
    tatDays: 9,
    minCibilScore: 700,
    minMonthlyIncome: 40000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "property_documents", "pan"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan", "business_registration"] },
    eligibilityCriteria: "Property and cashflow profile drive final approval.",
    prepaymentCharges: "As per sanction terms.",
    specialFeatures: ["business expansion support", "top-up"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
  {
    productType: "lap",
    lenderName: "Tata Capital",
    interestRateMin: 10.99,
    interestRateMax: 16,
    processingFeePercent: 2,
    minLoanAmount: 1200000,
    maxLoanAmount: 25000000,
    minTenureMonths: 36,
    maxTenureMonths: 180,
    tatDays: 8,
    minCibilScore: 690,
    minMonthlyIncome: 35000,
    documentsRequired: { salaried: ["salary_slip", "bank_statement", "property_documents", "pan"], selfEmployed: ["itr", "gst_returns", "bank_statement", "property_documents", "pan", "business_registration"] },
    eligibilityCriteria: "LTV generally up to 60%, subject to lender discretion.",
    prepaymentCharges: "As applicable in sanction letter.",
    specialFeatures: ["speedy processing", "SME-friendly"],
    lastUpdated: now,
    isActive: true,
    needsVerification: true,
  },
]

async function run() {
  const written = await upsertLendingProducts(seedProducts)
  console.log(`Seeded lending_products: ${written}`)
}

run().catch((error) => {
  console.error(error)
  process.exit(1)
})
